### PR TITLE
Create Ryan Reynolds.md

### PR DESCRIPTION
**Pull request by doniellesy**
A page under history-please/ history/ people dedicated to Canadian actor Ryan Reynolds.

### CODE REVIEW

**Comment by titaniumbones** [comment]
Looks good but file is ucrrently named just `Ryan Reynolds`. Can you add hte `.md` extension so we cna both preview the results? Then you will see some markup issues, and you cna try to fix them. Thx!

**Comment by doniellesy** [comment]
Oops! Sure thing.

**Comment by titaniumbones** [comment]
ok, thx, that's great. but now can you remove the leading `##` fro mthe regular paragraphs, and then add *one extra line* after each para? the text hould display fine afterwards.

**Comment by doniellesy** [comment]
Oh I see. Like this?

**Comment by titaniumbones** [comment]
yes, perfect!

**Pull request merged**
